#!/bin/sh -eu

: ${XDG_CONFIG_HOME:=$HOME/.config}
OPT_CONFIG="${MACRO_CONFIG:-"${XDG_CONFIG_HOME}/macro-wl/config.env"}"

! [ -e "$OPT_CONFIG" ] ||
  . "$OPT_CONFIG"

OPT_DEVICE="${MACRO_DEVICE:-}"
[ -z "${1:-}" ] ||
  OPT_DEVICE="$1"

[ -e "$OPT_DEVICE" ] || {
  echo "USAGE: ${0} <device>" >&2
  exit 1
}

OPT_QUIT_KEY="${MACRO_QUIT_KEY:-KEY_ESC}"

stdbuf -oL grabkb "$OPT_DEVICE" | while read -r _key
do
  [ "$_key" != "$OPT_QUIT_KEY" ] || \
    break

  _cmd="$(eval echo "\${MACRO_$_key:-}")"

  [ -n "$_cmd" ] || {
    echo " + ${_key} (unset)" >&2
    continue
  }

  echo " + ${_key} => ${_cmd}" >&2
  sh -c "$_cmd" &
done
